apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-0
data:
  http: "8000"
  host: "kafka.default.svc.cluster.local"
  port: "9092"
  topic: "test"
  partition: "0"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-1
data:
  http: "8001"
  host: "kafka.default.svc.cluster.local"
  port: "9092"
  topic: "test"
  partition: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-2
data:
  http: "8002"
  host: "kafka.default.svc.cluster.local"
  port: "9092"
  topic: "test"
  partition: "2"


